module.exports = {
  "SUCC": "Success",
  "MISSING_PARAMS": "Missing Parameters.",
  "SOMETHING_WRONG": "Oops! Something went wrong.",
  "LOGIN_SUCC": "Login Successfully.",
  "NO_USR_FND": "No user found.",
  "UNAUTH_USR": "Unauthorised user.",
  "DEACT_USR_ACCT": "This account has been deactivated. Please contact to admin.",
  "TOKN_MIS_MTCH": "Access token mismatch",
  "SESSION_EXP": "Session expire, Please login again.",
  "MISS_ACC_TKN": "Missing access token.",
  "LINK_EXP": "Your one time link is expire now, Please contact to admin.",
  "NO_DOCT_FND": "No doctor found.",
  "NO_NUTRI_FND": "No nutrition found.",
  "NO_CHF_FND": "No chef found.",
  "INV_PASS": "Invalid Password.",
  "LINK_SEND_SUCC": "Reset password link has been sent to your email.",
  "USER_INACTIVE": "This account has been deactivated. Please contact to admin.",
  "ONE_TIME_LINK_EXPIRE": "Your reset password link has been expired please try again",
  "PASSWORD_UPDATE_SUCCESS": "Password change successfully.",
  "SIGNUP_SUCC": "User registerd successfully.",
  "USR_ALRDY_EXIST": "User already exist.",
  "NP_PLN_FND": "No plan found.",
  "CHG_PASS_SUCC": "Password changed successfully.",
  "CUR_PASS_NOT_MTCH": "Current password is wrong.",
  "DEACT_SUCC": "Your account has been deactivated successfully.",
  "FED_SENT_SUCC": "Thanks for giving feedback.",
  "EMAIL_NOT_REG": "This email is not registerd with us.",
  "NEW_DOCT_ADDED": "New doctor added successfully.",
  "EMAIL_ALRDY": "Email address you have entered is already registered.",
  "PASS_SET_SUCC": "Password set successfully.",
  "PRO_UPDT_SUCC": "Profile updated successfully.",
  "NO_NUTRI_FND": "No nutririon found.",
  "INV_TYP": "Invalid Type.",
  "ALRDY_FAV": "This blog is already in favourite.",
  "UNFV_BLG_SUCC": "Blog unfavourite successfully.",
  "FAV_BLG_SUCC": "Blog favourite successfully.",
  "ALRDY_UNFAV": "This blog is already in unfavourite.",
  "NO_BLG_FND": "No blog found.",
  "BSC_DETL_UPDT_SUCC": "Basic details updated successfully.",
  "GOL_UPDT_SUCC": "Goal updated successfully.",
  "PER_DET_UPDT_SUCC": "Personal details updated successfully.",
  "NO_CAT_FND": "No category found.",
  "NO_VDO_FND": "No video found.",
  "ADD_ADDED_SUCC": "Address added successfully.",
  "NO_ADD_FND": "No address found.",
  "ADD_DLT_SUCC": "Address deleted successfully.",
  "ADD_UPDT_SUCC": "Address updated successfully.",
  "NO_TEST_FOUND": "No test found.",
  "NO_REC_FOUND": "No record found.",
  "USR_ACT_ADD_SUCC": "User activity added successfully.",
  "USR_ACT_UPDT_SUCC": "User activity updated successfully.",
  "USR_PLAN_UPDT_SUCC": "Tier plan upgrade successfully.",
  "USR_QUESTNR_UPDT_SUCC": "Questionnaire updated successfully.",
  "PRO_IMG_UPDT_SUCC": "Profile image updated successfully.",
  "NO_TIPS_FOUND": "No tips available.",
  "NO_USR_ACTVTY_FOUND": "No activity available.",
  "NEW_NUTRTN_ADDED": "New nutrition added successfully.",
  "NEW_CHEF_ADDED": "New chef added successfully.",
  "NEW_BLG_ADDED": "New blog added successfully.",
  "BLG_UPDT_SUCC": "Blog updated successfully.",
  "APPO_SCH_SUCC": "Appointment scheduled successfully.",
  "APPO_RESCH_SUCC": "Appointment Re-scheduled successfully.",
  "SLOTS_BUSY": "This slot is booked by other patient please choose another slots.",
  "INV_DVC_TYP": "Invalid device type.",
  "NEW_LABASSTNT_ADDED": "New lab assistant added successfully.",
  "NO_APPO_FND": "No appointment found.",
  "NEW_REPORT_ADDED": "New test report added successfully.",
  "SLOTS_UPD_SUCC": "Slot updated successfully.",
  "USR_PERMSN_UPDT_SUCC": "User role updated successfully.",
  "HOL_DT_ADD_SUCC": "Holiday date added successfully.",
  "HOLD_DT_DLT_SUCC": "Holiday date deleted successfully.",
  "HLD_DT_ALRDY_EXIST": "Holiday date already exist.",
  "NO_INGR_FND": "No ingredients found.",
  "REC_ADD_SUCC": "Recipe added successfully.",
  "NO_RECP_FND": "No recipe found.",
  "NEW_CAT_ADDED": "New category added successfully.",
  "CAT_UPDT_SUCC": "Category updated successfully.",
  "NEW_ADMN_ADDED": "New admin added successfully.",
  "NO_ADMN_FND": "No admin found.",
  "RECORD_ADD_SUCC": "Record added successfully",
  "UPLD_VALID_FORMAT_DATA": "Please upload file with valid data/format.",
  "TEST_REPORT_UPDT_SUCC": "Test report updated successfully.",
  "NOT_ADDED_SUCC": "Notes added successfully.",
  "NOT_UPDT_SUCC": "Notes updated successfully.",
  "NOT_DLT_SUCC": "Note deleted successfully.",
  "NO_EXER_FND": "No exercise found.",
  "NEW_TP_ADDED": "New tip added successfully.",
  "TP_DLT_SUCC": "Tip deleted successfully.",
  "TP_UPDT_SUCC": "Tip updated successfully.",
  "NO_RECEVR_FND": "No receiver found.",
  "YOU_NOT_AUTH_TO_DLT_TP": "You are not authorized to delete this tip.",
  "YOU_NOT_AUTH_TO_UPDT_TP": "You are not authorized to update this tip.",
  "TP_UPDT_SUCC": "Tip updated successfully.",
  "NO_CONT_FND": "No content found.",
  "CONT_UPDT_SUCC": "Content updated successfully.",
  "NEW_COKVID_ADDED": "New cooking video added successfully."
}
